#!/usr/bin/env bash
#
# Container entrypoint: bring up the embedded single-node Kafka broker, make sure the
# notification topic exists, then run the Spring Boot app in the foreground.
#
# Everything below is overridable with env vars so the same image runs locally and on Render.

set -euo pipefail

KAFKA_HOME="${KAFKA_HOME:-/opt/kafka}"
KAFKA_DATA_DIR="${KAFKA_DATA_DIR:-/var/lib/kafka/data}"
KAFKA_NODE_ID="${KAFKA_NODE_ID:-1}"
KAFKA_PORT="${KAFKA_PORT:-9092}"
KAFKA_CONTROLLER_PORT="${KAFKA_CONTROLLER_PORT:-9093}"
KAFKA_TOPIC_NOTIFICATIONS="${KAFKA_TOPIC_NOTIFICATIONS:-blogger-hub-notifications}"
KAFKA_TOPIC_PARTITIONS="${KAFKA_TOPIC_PARTITIONS:-3}"
KAFKA_TOPIC_RETENTION_MS="${KAFKA_TOPIC_RETENTION_MS:-604800000}"
KAFKA_STARTUP_TIMEOUT_SECONDS="${KAFKA_STARTUP_TIMEOUT_SECONDS:-120}"

# A KRaft cluster ID is just a stable 16-byte base64 token. It must not change between restarts
# when a persistent disk is attached, or the broker will refuse to open the existing log dir.
KAFKA_CLUSTER_ID="${KAFKA_CLUSTER_ID:-MkU3OEVBNTcwNTJENDM2Qk}"

# Loopback only, deliberately: Render exposes exactly one port per service, and an internet-
# reachable PLAINTEXT broker with no auth would be an open door.
BOOTSTRAP="127.0.0.1:${KAFKA_PORT}"

# Regenerated on every boot in a writable location. The distribution's own server.properties is
# the ZooKeeper-era template and appending to it (as the previous version of this script did)
# both mixes in stale defaults and grows the file on every restart.
KAFKA_CONFIG="${KAFKA_CONFIG:-/tmp/kafka-server.properties}"

log() { echo "[start.sh] $*"; }

# --------------------------------------------------------------------------------------------
# 1. Kafka configuration
# --------------------------------------------------------------------------------------------
mkdir -p "${KAFKA_DATA_DIR}"

if [ ! -w "${KAFKA_DATA_DIR}" ]; then
  log "FATAL: ${KAFKA_DATA_DIR} is not writable by $(id -un)."
  log "If you attached a Render disk here, mount it somewhere this user owns or run as root."
  exit 1
fi

cat > "${KAFKA_CONFIG}" <<EOF
# Generated by start.sh — do not edit, changes are overwritten on every boot.
process.roles=broker,controller
node.id=${KAFKA_NODE_ID}
controller.quorum.voters=${KAFKA_NODE_ID}@127.0.0.1:${KAFKA_CONTROLLER_PORT}

listeners=PLAINTEXT://127.0.0.1:${KAFKA_PORT},CONTROLLER://127.0.0.1:${KAFKA_CONTROLLER_PORT}
advertised.listeners=PLAINTEXT://127.0.0.1:${KAFKA_PORT}
listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
inter.broker.listener.name=PLAINTEXT
controller.listener.names=CONTROLLER

log.dirs=${KAFKA_DATA_DIR}

# Single broker, so nothing can be replicated anywhere — every replication factor must be 1 or
# the internal topics fail to create and the broker never becomes ready.
offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1
default.replication.factor=1
min.insync.replicas=1

# Topics are created explicitly below; auto-creation would silently mask a typo in a topic name.
auto.create.topics.enable=false

# Trimmed from the stock defaults because this broker shares a container with the app.
num.network.threads=2
num.io.threads=2
background.threads=4
num.recovery.threads.per.data.dir=1
log.segment.bytes=134217728
log.retention.check.interval.ms=300000

# The stock 3s rebalance delay just adds 3s to every cold start for a single-consumer group.
group.initial.rebalance.delay.ms=0
EOF

# --------------------------------------------------------------------------------------------
# 2. Format the log directory (no-op once formatted, so it is safe with or without a disk)
# --------------------------------------------------------------------------------------------
log "Formatting Kafka storage in ${KAFKA_DATA_DIR} (cluster ${KAFKA_CLUSTER_ID})..."
"${KAFKA_HOME}/bin/kafka-storage.sh" format \
  --cluster-id "${KAFKA_CLUSTER_ID}" \
  --config "${KAFKA_CONFIG}" \
  --ignore-formatted

# --------------------------------------------------------------------------------------------
# 3. Start the broker
# --------------------------------------------------------------------------------------------
log "Starting Kafka broker..."
"${KAFKA_HOME}/bin/kafka-server-start.sh" "${KAFKA_CONFIG}" &
KAFKA_PID=$!

log "Waiting for the broker to accept connections on ${BOOTSTRAP}..."
deadline=$(( SECONDS + KAFKA_STARTUP_TIMEOUT_SECONDS ))
until "${KAFKA_HOME}/bin/kafka-topics.sh" --bootstrap-server "${BOOTSTRAP}" --list >/dev/null 2>&1; do
  if ! kill -0 "${KAFKA_PID}" 2>/dev/null; then
    log "FATAL: Kafka exited during startup. See the broker log above."
    exit 1
  fi
  if [ "${SECONDS}" -ge "${deadline}" ]; then
    log "FATAL: Kafka was not ready within ${KAFKA_STARTUP_TIMEOUT_SECONDS}s."
    kill -TERM "${KAFKA_PID}" 2>/dev/null || true
    exit 1
  fi
  sleep 3
done
log "Kafka is ready."

# --------------------------------------------------------------------------------------------
# 4. Create the notification topic
# --------------------------------------------------------------------------------------------
log "Ensuring topic '${KAFKA_TOPIC_NOTIFICATIONS}' exists..."
"${KAFKA_HOME}/bin/kafka-topics.sh" \
  --bootstrap-server "${BOOTSTRAP}" \
  --create --if-not-exists \
  --topic "${KAFKA_TOPIC_NOTIFICATIONS}" \
  --partitions "${KAFKA_TOPIC_PARTITIONS}" \
  --replication-factor 1 \
  --config "retention.ms=${KAFKA_TOPIC_RETENTION_MS}"

# --------------------------------------------------------------------------------------------
# 5. Start the application
# --------------------------------------------------------------------------------------------
APP_ARGS=()

# Render mounts Secret Files under /etc/secrets. Using one keeps credentials out of both the
# image and the dashboard env list; if it isn't there, plain env vars are expected instead.
SECRETS_CONFIG="${SPRING_SECRETS_CONFIG:-/etc/secrets/application-render.yaml}"
if [ -f "${SECRETS_CONFIG}" ]; then
  log "Loading additional configuration from ${SECRETS_CONFIG}"
  APP_ARGS+=("--spring.config.additional-location=file:${SECRETS_CONFIG}")
fi

# The app talks to the broker over loopback unless something else is configured.
export KAFKA_BOOTSTRAP_SERVERS="${KAFKA_BOOTSTRAP_SERVERS:-${BOOTSTRAP}}"
export KAFKA_TOPIC_NOTIFICATIONS

log "Starting Spring Boot on port ${PORT:-8080}..."
# shellcheck disable=SC2086 # JAVA_OPTS is intentionally word-split into separate JVM flags.
java ${JAVA_OPTS:-} -jar /app/app.jar "${APP_ARGS[@]}" &
APP_PID=$!

# Render sends SIGTERM to PID 1 on shutdown. Draining the app first and the broker second gives
# in-flight HTTP requests a chance to finish and lets Kafka close its log segments cleanly,
# which avoids a slow recovery scan on the next boot when a disk is attached.
shutdown() {
  log "Shutting down..."
  kill -TERM "${APP_PID}" 2>/dev/null || true
  wait "${APP_PID}" 2>/dev/null || true
  kill -TERM "${KAFKA_PID}" 2>/dev/null || true
  wait "${KAFKA_PID}" 2>/dev/null || true
  exit 0
}
trap shutdown TERM INT

# If either process dies the container should die with it, so Render restarts a clean instance
# rather than serving a half-broken one.
set +e
wait -n "${APP_PID}" "${KAFKA_PID}"
EXIT_CODE=$?
set -e
log "A managed process exited (code ${EXIT_CODE}); tearing down the container."
kill -TERM "${APP_PID}" "${KAFKA_PID}" 2>/dev/null || true
exit "${EXIT_CODE}"
