# Configuration file for the development environment.

# MongoDB configuration
MONGODB_USERNAME: mongodb_username
MONGODB_PASSWORD: mongodb_password
MONGODB_URI: mongodb_uri

# JWT configuration
ACCESS_TOKEN_SECRET: jwt_access_token_secret
REFRESH_TOKEN_SECRET: jwt_refresh_token_secret
ACCESS_TOKEN_EXPIRATION_MINUTES: access_token_expiration_minutes # 15
REFRESH_TOKEN_EXPIRATION_DAYS: refresh_token_expiration_days # 7