spring:
  application:
    name: blogger-hub

  data:
    mongodb:
      uri: ${MONGODB_URI}

jwt:
  auth:
    accessTokenSecret: ${ACCESS_TOKEN_SECRET}
    refreshTokenSecret: ${REFRESH_TOKEN_SECRET}
    refreshTokenExpirationDays: ${REFRESH_TOKEN_EXPIRATION_DAYS}
    accessTokenExpirationMinutes: ${ACCESS_TOKEN_EXPIRATION_MINUTES}